source 'https://github.com/CocoaPods/Specs.git'

target 'FSVoiceBubble', :exclusive => true do
  pod "FSVoiceBubble", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FSVoiceBubble", :path => "../"

  
end
